# Netlify Configuration for Binary Cooking Game - FIXED
[build]
  # Build command - no need to cd into functions
  command = "npm install --prefix netlify/functions"
  
  # Publish directory
  publish = "."
  
  # Functions directory - CRITICAL PATH
  functions = "netlify/functions"

[functions]
  # Node.js runtime version
  node_bundler = "esbuild"
  
  # External node modules (for MongoDB)
  external_node_modules = ["mongodb"]

# Environment variables (set in Netlify UI - already done ✅)
# MONGODB_URI = your-mongodb-uri

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"

# Force HTTPS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"